auction/lib/auction_web/router.ex
defmodule AuctionWeb.Router do
  use AuctionWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug AuctionWeb.Authenticator
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AuctionWeb do
    pipe_through :browser

    get "/", ItemController, :index

    resources "/items", ItemController, except: [:delete] do
      resources "/bids", BidController, only: [:create] # nested resource
    end

    resources "/users", UserController, only: [:show, :new, :create]
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  scope "/api", AuctionWeb.API do
    pipe_through :api

    resources "/items", ItemController, only: [:index, :show]
  end
end

auction/lib/auction/item.ex
defmodule Auction.Item do
  use Ecto.Schema
  import Ecto.Changeset # instead of prefacing validations with `Ecto.Changeset`

  schema "items" do
    field :title, :string
    field :description, :string
    field :ends_at, :utc_datetime
    has_many :bids, Auction.Bid
    timestamps()
  end

  def changeset(item, params \\ %{}) do
    item
    |> cast(params, [:title, :description, :ends_at]) # only these fields can be changed
    |> validate_required(:title)
    |> validate_length(:title, min: 3, max: 100)
    |> validate_length(:description, max: 255)
    |> validate_change(:ends_at, &validate/2) # calls custom validation below
  end

  defp validate(:ends_at, ends_at_date) do
    case DateTime.compare(ends_at_date, DateTime.utc_now()) do
      :lt -> [ends_at: "ends_at cannot be in the past"] # "less than"
      _ -> [] # everything else
    end
  end
end

auction/lib/auction_web/controllers/api/item_controller.ex
defmodule AuctionWeb.API.ItemController do
  use AuctionWeb, :controller

  def index(conn, _params) do
    items = Auction.list_items
    render(conn, "index.json", items: items)
  end

  def show(conn, %{"id" => id}) do
    item = Auction.get_item_with_bids(id)
    render(conn, "show.json", item: item)
  end
end

auction/lib/auction_web/controllers/item_controller.ex
defmodule AuctionWeb.ItemController do
  use AuctionWeb, :controller

  def index(conn, _params) do
    items = Auction.list_items
    render(conn, "index.html", items: items)
  end

  def show(conn, %{"id" => id}) do
    item = Auction.get_item_with_bids(id)
    bid = Auction.new_bid
    render(conn, "show.html", item: item, bid: bid)
  end

  def new(conn, _parms) do
    item = Auction.new_item
    render(conn, "new.html", item: item)
  end

  def create(conn, %{"item" => item_params}) do
    case Auction.insert_item(item_params) do
      {:ok, item} -> redirect(conn, to: Routes.item_path(conn, :show, item))
      {:error, item} -> render(conn, "new.html", item: item)
    end
  end

  def edit(conn, %{"id" => item_id}) do
    item = Auction.edit_item(item_id)
    render(conn, "edit.html", item: item)
  end

  def update(conn, %{"id" => item_id, "item" => item_params}) do
    item = Auction.get_item(item_id)
    case Auction.update_item(item, item_params) do
      {:ok, item} -> redirect(conn, to: Routes.item_path(conn, :show, item))
      {:error, item} -> render(conn, "edit.html", item: item)
    end
  end
end

auction/lib/auction_web/views/item_view.ex
defmodule AuctionWeb.ItemView do
  use AuctionWeb, :view

  def t, do: DateTime.utc_now
end

auction/lib/auction_web/templates/item/edit.html.eex
<h1>Edit <%= @item.data.title %></h1> <!-- need to call `.data` because @item is a changeset -->

<%= render("form.html", item: @item, action: Routes.item_path(@conn, :update, @item.data)) %>

auction/lib/auction_web/templates/item/form.html.eex
<%= form_for @item, @action, fn f -> %>
  <%= if @item.action do %>
    <div class="alert alert-danger">
      Unfortunately, there are errors in your submission. Please correct them below.
    </div>
  <% end %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :description %>
  <%= textarea f, :description %>
  <%= error_tag f, :description %>

  <%= label f, :ends_at, "Auction ends at" %>
  <%= datetime_select f, :ends_at, default: {{t().year, t().month, t().day}, {t().hour, t().minute, 0}}, year: [options: t().year..(t().year + 5)] %>
  <%= error_tag f, :ends_at %>

  <div>
    <%= submit "Submit" %>
  </div>
<% end %>

auction/lib/auction_web/templates/item/index.html.eex
<ul>
  <%= for item <- @items do %>
    <li>
      <strong><%= link(item.title, to: Routes.item_path(@conn, :show, item)) %></strong>: <%= item.description %>
    </li>
  <% end %>
</ul>

auction/lib/auction_web/templates/item/new.html.eex
<h1>New Item</h1>

<%= render("form.html", item: @item, action: Routes.item_path(@conn, :create)) %>

auction/lib/auction_web/templates/item/show.html.eex
<h1><%= @item.title %></h1>

<ul>
  <li><strong>Description:</strong> <%= @item.description %></li>
  <li><strong>Auction ends at:</strong> <%= @item.ends_at %></li>
</ul>

<div style="display: flex; flex-direction: row;">
  <div style="flex: 1;">
    <h2>Current bids:</h2>
    <%= for bid <- @item.bids do %> <!-- "comprehension" iterates over bids -->
      <p><%= integer_to_currency(bid.amount) %> <em>from "<%= bid.user.username %>"</em></p>
    <% end %>
  </div>

  <div style="flex: 1;">
    <%= if @current_user do %>
      <h2>Place a bid!</h2>

      <%= form_for @bid, Routes.item_bid_path(@conn, :create, @item), fn f -> %>
        <%= if @bid.action do %>
          <div class="alert alert-danger">
            Unfortunately, there are errors in your submission. Please correct them below.
          </div>
        <% end %>

        <div class="form-group">
          <%= label f, :amount, "Bid amount", class: "control-label" %>
          <%= error_tag f, :amount %>
          <%= number_input f, :amount, class: "form-control" %>
        </div>

        <%= submit "Submit", class: "btn btn-primary" %>
      <% end %>
    <% end %>
  </div>
</div>